name: eb_clean_cli
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
 path: ^1.8.1
 args: ^2.1.0
 glob: ^2.0.2
 lcov_parser: ^0.1.2
 mason: ^0.1.0-dev.21
 mason_logger: ^0.1.0-dev.8
 meta: ^1.3.0
 pub_updater: ^0.2.1
 pubspec_parse: ^1.2.0
 universal_io: ^2.0.4
 usage: ^4.0.2
 recase: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1

executables:
 eb_clean: